- name: GitHub用のSSH秘密鍵を転送する
  copy:
    src:  ~/.ssh/github
    dest: /root/.ssh/
    mode: 0600

- name: configファイルの素を設置する
  file:
    src:   ~/dropbox/dotfiles/.ssh/config.d
    dest:  /root/.ssh/config.d
    state: link

- name: 一時的にconfigファイルを設置する
  # GitHubからdotenvとか持ってくるため
  template:
    src:  config
    dest: /root/.ssh/
