- name: 設定ファイルを配置する
  copy:
    src:  ~/dev/devenv/dotfiles/{{ item }}
    dest: /root/{{ item }}
  with_items:
    - .ackrc
    - .aliases
    - .ctags
    - .gemrc
    - .gvimrc
    - .pryrc
    - .railsrc
    - .spring.rb
    - .tmux.conf
    - .vim
    - .vimrc
    - .zlogin
    - .zsh
    - .zshrc
    - bin
