- name: ntpをインストールする
  apt:
    name:  ntp
    state: present

- name: ntp.confを編集する
  template:
    src:  ntp.conf
    dest: /etc/ntp.conf

- name: ntpを再起動する
  service:
    name:  ntp
    state: restarted

- name: タイムゾーンを変更する (/etc/localtimeを置き換える)
  command: cp -f /usr/share/zoneinfo/Japan /etc/localtime

- name: タイムゾーンを変更する (/etc/timezoneを編集する)
  template:
    src:  timezone
    dest: /etc/timezone
