- name: Node.js関連のパッケージをインストールする
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - nodejs
    # /usr/bin/node でNode.jsを動かすためにインストールする
    # http://plaidzooks.tumblr.com/post/36894116867/using-node-js-on-debian-ubuntu-systems
    - nodejs-legacy
    - npm
