- name: CLIスクリプトをダウンロードする
  get_url:
    dest: /root/bin/dropbox.py
    url:  https://www.dropbox.com/download?dl=packages/dropbox.py
    mode: 0755

- name: Dropboxをインストールする
  shell: curl -L "https://www.dropbox.com/download?plat=lnx.x86_64" | tar -C $HOME -xzf -
  args:
    creates: /root/.dropbox-dist/dropboxd

- name: Configure KDE to autostart dropboxd
  file: path={{home}}/.kde/Autostart/dropboxd src={{home}}/.dropbox-dist/dropboxd state=link
  -
    name: Check dropboxd status
    command: /usr/local/bin/dropbox.py status
    register: status
  -
    name: Start dropboxd
    shell: /usr/local/bin/dropbox.py start >/dev/null 2>&1
    when: status.stdout == "Dropbox isn't running!"
