- name: MySQLをインストールする
  apt:
    pkg:   '{{ item }}'
    state: installed
  with_items:
    - mysql-server-5.6
    - mysql-client-core-5.6 # mysql-client-5.6 をインストールする前にインストールしないとエラーになる
    - mysql-client-5.6
    - libmysqlclient-dev # mysql2 gemをインストールするときに必要になる

- name: MySQLの設定ファイルを更新する
  template:
    src:  my.cnf
    dest: /etc/mysql/my.cnf

- name: ib_logfilesを削除する
  # http://app.road.jp.net/?p=1423
  shell: rm -rf /var/lib/mysql/ib_logfile*

- name: MySQLを再起動する
  service:
    name:  mysql
    state: restarted
